import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { Navbar } from './(main)/_components/navbar'

const roboto = Roboto({ 
  weight: "400",
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <div className='bg-[#fffff1] text-[#333333]'>
        <Navbar />
        <main className={roboto.className} >
          {children}
        </main>
      </div>
    </html>
  )
}
