import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from './(main)/_components/navbar'
import { Footer } from './(main)/_components/footer'

const inter = Inter({ 
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <div className='bg-[#fffff1] text-[#333333]'>
        <main className={inter.className} >
          {children}
        </main>
      </div>
    </html>
  )
}
